### ISSUE TITLE
Altair GraphQL Client has other platform support

### ISSUE THREAD

**Issue by imolorhe** [railt/application#1]
Hello,

In the "Exploring with GraphQL" page, you listed Altair GraphQL Client as a chrome extension. It has more binaries for all the desktop platforms and also extension for FireFox too. :)

https://altair.sirmuel.design/

Also those are GraphQL tools, not a GraphiQL tools. GraphiQL is a GraphQL tool of its own.

**Comment by SerafimArts** [comment]
@imolorhe Well it seems this is not particularly important in the example, is it not? =)

...especially with the latest updates, this example does not seem to be particularly working

**Comment by imolorhe** [comment]
Oh okay. I was just pointing it out. 😁
